### ISSUE TITLE
GraphQL Config + GraphQL CLI

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#120]
It'd be great to use [graphql-config](https://github.com/kamilkisiela/graphql-config) with [graphql-cli](https://github.com/Urigo/graphql-cli) to take advantage of the code generation for type schemas through package.json scripts rather than using IDEs config (webstorm/vscode/etc), this would improve the development workflow quite a lot.

Also, I'm having a hard time trying to integrate `graph-config` on vscode, since they're released a brand new version recently I can't find a vscode extension that properly works with it, having a script to generate the schema and types would be super helpful.

https://github.com/stephen/vscode-graphql/issues/27
https://github.com/kamilkisiela/graphql-config/issues/555
https://github.com/Urigo/graphql-cli/issues/1249

We could do something like:

```yml
schema: 
  - https://graphcms-url:
      headers:
        Authorization: key
extensions:
  codegen:
    generates:
      ./schema.graphql:
        plugins:
          - schema-ast
        config:
          commentDescriptions: true
      ./src/common/types/data/DataTypes.tsx:
        plugins:
          - typescript
          - typescript-operations
```
and then

```json
"scripts": {
   "codegen": "npx graphql-codegen"
}
```

With this in place we won't need to maintain our own types (GraphCMS) since everything will be pulled out directly from the source. (Single Source of Truth)

Also we need to [migrate](https://graphql-config.com/migration) the `.graphqlconfig` file to the new graphql-config structure.
