### ISSUE TITLE
Treat NRN own preset branches as "production" branches (Github Actions)

### ISSUE THREAD

**Issue by Vadorequest** [UnlyEd/next-right-now#75]
I'd like preset branches to be treated as production branches.

For example, pushing to https://github.com/UnlyEd/next-right-now/tree/v2-mst-aptd-gcms-lcz-sty would trigger a Vercel `production` deployment.

This would help enforce any work should be done under a different branch, and then merged into preset branch(es). 

This way, each branch preset would automatically use a production deployment.
Any other branch would be treated as staging.

Also, I have a few concerns regarding projects created using NRN. I wouldn't want the default configuration to deploy to production when using our internal naming, that could be harmful.

So, ideally, I'd want to enforce that NRN-specific rules can only be triggered on NRN.

I don't know if it's technically possible and I've opened a question at https://github.community/t/is-it-possible-to-conditionally-run-an-action-based-on-the-repo-name-url/116115

**Comment by Vadorequest** [comment]
Answer given at https://github.community/t/is-it-possible-to-conditionally-run-an-action-based-on-the-repo-name-url/116115/2?u=vadorequest

```yml
name: Deploy to Zeit (staging)

on:
  push:
    branches-ignore:
      - 'master'
jobs:
  job1:
    if: github.repository=='orgname/reponame'     #check the org/reponame here to execute the job conditonally.
```

So, it seems technically doable. Need to think a bit more about how to do it exactly, I'm thinking using distinct files (dedicated to NRN presets branches), but I'm not sure it's the best course of action.
